# Exercise

Ok, its time to practice what we just covered in the Opening and reading files chapter. We are going to use pandas to open a csv and then proceed to carry out a bit.

Let's start off by downloading the csv combined_indicators_for_nigeria_2. This is a csv file, read the file using pandas.

- Print the first 5 columns in the dataframe and the name of all the columns
- in addition to this change the column <strong><i>country_iso3</i></strong> to <strong><i>country iso code</i></strong>

In [ ]:
# path = 'C://Users//User//Documents//GradientBoostCurriculum//GradientBoostIntrotoDS//Introduction to Python//Chapter 3 - File Handling, Introduction to Pandas//combined_indicators_for_nigeria_2.csv'
# import pandas as pd
# df = pd.read_csv(path)

#answer here
import pandas as pd
file = "combined_indicators_for_nigeria_2.csv"

df = pd.read_csv(file)
df.rename(columns={'country_iso3':'country iso code'}, inplace=True)
df.head()

# Question 1

Select data in your dataframe where the indicator name is;
- "Net bilateral aid flows from DAC donors, Australia (current US$) or
- Net bilateral aid flows from DAC donors, United Kingdomor
- Net bilateral aid flows from DAC donors, United States or 
- Net bilateral aid flows from DAC donors, European Union institutions

Save this as western_dac_donors

In [55]:
#answer here
donors = ["Net bilateral aid flows from DAC donors, Australia (current US$)", "Net bilateral aid flows from DAC donors, United Kingdom", "Net bilateral aid flows from DAC donors, United States", "Net bilateral aid flows from DAC donors, European Union institutions"]

western_dac_donors = df[df.indicator_name.apply(lambda x: x in donors)]
western_dac_donors.head()

,country_name,country iso code,year,indicator_name,indicator_code,value
1760,Nigeria,NGA,2017,"Net bilateral aid flows from DAC donors, Austr...",DC.DAC.AUSL.CD,8780000.0
1761,Nigeria,NGA,2016,"Net bilateral aid flows from DAC donors, Austr...",DC.DAC.AUSL.CD,1680000.0
1762,Nigeria,NGA,2015,"Net bilateral aid flows from DAC donors, Austr...",DC.DAC.AUSL.CD,2090000.0
1763,Nigeria,NGA,2014,"Net bilateral aid flows from DAC donors, Austr...",DC.DAC.AUSL.CD,2380000.0
1764,Nigeria,NGA,2013,"Net bilateral aid flows from DAC donors, Austr...",DC.DAC.AUSL.CD,3670000.0

# Question 2

Great, now select the rows where the indicator_name relates to Net officual flows from UN agencies, save this subset as un_agencies_donor

In [56]:
#answer here

un_agencies_donor = df[df['indicator_name'].apply(lambda x: 'Net official flows from UN agencies,' in x)]
un_agencies_donor.head()

,country_name,country iso code,year,indicator_name,indicator_code,value
2894,Nigeria,NGA,2013,"Net official flows from UN agencies, FAO (curr...",DT.NFL.FAOG.CD,440000.0
2895,Nigeria,NGA,2017,"Net official flows from UN agencies, IAEA (cur...",DT.NFL.IAEA.CD,470000.0
2896,Nigeria,NGA,2016,"Net official flows from UN agencies, IAEA (cur...",DT.NFL.IAEA.CD,510000.0
2897,Nigeria,NGA,2015,"Net official flows from UN agencies, IAEA (cur...",DT.NFL.IAEA.CD,400000.0
2898,Nigeria,NGA,2014,"Net official flows from UN agencies, IAEA (cur...",DT.NFL.IAEA.CD,640000.0

# Question 3

Select all the rows in un_agencies_donor where the year is greater than or equal to 2015, sort these rows by <strong>value</strong> in descending order ie. starting with the largest value

In [63]:
#answer here

un_agencies_donor = un_agencies_donor[un_agencies_donor['year'].apply(lambda x: x>2015 or x==2015)].sort_values(by='value', ascending=False)
un_agencies_donor.head()

,country_name,country iso code,year,indicator_name,indicator_code,value
2956,Nigeria,NGA,2016,"Net official flows from UN agencies, UNICEF (c...",DT.NFL.UNCF.CD,57920000.0
2955,Nigeria,NGA,2017,"Net official flows from UN agencies, UNICEF (c...",DT.NFL.UNCF.CD,55020000.0
2957,Nigeria,NGA,2015,"Net official flows from UN agencies, UNICEF (c...",DT.NFL.UNCF.CD,48950000.0
2907,Nigeria,NGA,2017,"Net official flows from UN agencies, IFAD (cur...",DT.NFL.IFAD.CD,30840000.0
2908,Nigeria,NGA,2016,"Net official flows from UN agencies, IFAD (cur...",DT.NFL.IFAD.CD,19600000.0

# Question 4
How much money did Nigeria receive from 
- i.) WHO in 2016 and 2017
- ii.) bilateral aid flows from DAC donor, United Kingdom in 2016 and 2017

In [82]:
import numpy as np

WHO = df[df['indicator_name'] == 'Net official flows from UN agencies, WHO (current US$)']#
WHO = WHO[WHO['year'].apply(lambda x: x==2016 or x==2017)]
WHO_funds = WHO['value'].agg(np.sum)
print('The total mony received by Nigeria from the WHO from 2016 to 2017 is {}'.format(WHO_funds))

The total mony received by Nigeria from the WHO from 2016 to 2017 is 7180000.0

In [83]:
uk = df[df['indicator_name'] == 'Net bilateral aid flows from DAC donors, United Kingdom (current US$)']
uk = uk[uk['year'].apply(lambda x: x==2016 or x==2017)]
uk_funds = uk['value'].agg(np.sum)
print('The total mony received by Nigeria from bilateral aid flows from DAC donor, United Kingdom in 2016 and 2017 is {}'.format(uk_funds))

The total mony received by Nigeria from bilateral aid flows from DAC donor, United Kingdom in 2016 and 2017 is 852610000.0

# Question 5

- i.) Calculate the mean value of all net official flows from UN agencies in 2016
- ii.) Calculate the median value of all net official flows from UN agencies in 2016

In [98]:
#answer here

un_agencies_donor.value.agg([np.mean, np.median])
un_agencies_donor_2016 = un_agencies_donor[un_agencies_donor.year.apply(lambda x: x==2016)]
un_agencies_donor_2016

,country_name,country iso code,year,indicator_name,indicator_code,value
2956,Nigeria,NGA,2016,"Net official flows from UN agencies, UNICEF (c...",DT.NFL.UNCF.CD,57920000.0
2908,Nigeria,NGA,2016,"Net official flows from UN agencies, IFAD (cur...",DT.NFL.IFAD.CD,19600000.0
3041,Nigeria,NGA,2016,"Net official flows from UN agencies, UNDP (cur...",DT.NFL.UNDP.CD,9690000.0
3091,Nigeria,NGA,2016,"Net official flows from UN agencies, UNFPA (cu...",DT.NFL.UNFP.CD,5970000.0
3182,Nigeria,NGA,2016,"Net official flows from UN agencies, WHO (curr...",DT.NFL.WHOL.CD,2670000.0
2943,Nigeria,NGA,2016,"Net official flows from UN agencies, UNAIDS (c...",DT.NFL.UNAI.CD,2390000.0
3170,Nigeria,NGA,2016,"Net official flows from UN agencies, WFP (curr...",DT.NFL.WFPG.CD,1390000.0
2937,Nigeria,NGA,2016,"Net official flows from UN agencies, ILO (curr...",DT.NFL.ILOG.CD,520000.0
2896,Nigeria,NGA,2016,"Net official flows from UN agencies, IAEA (cur...",DT.NFL.IAEA.CD,510000.0

In [99]:
mean = un_agencies_donor_2016.value.agg([np.mean]).values[0]
median = un_agencies_donor_2016['value'].agg([np.median]).values[0]

print("The mean and median of the value of all net official flows from UN agencies in 2016 are {} and {} respectively.".format(mean, median))

The mean and median of the value of all net official flows from UN agencies in 2016 are 11184444.444444444 and 2670000.0 respectively.